### ISSUE TITLE
Unhandled exception when running in directory without pyproject.toml

### ISSUE THREAD

**Issue by ssteinerx** [nahco314/poetry2rye#2]
I just ran it wherever I happened to be after `pipx install`ing it.

It wasn't a python project, it can't possibly work, there is no pyproject.toml.

That said, catching the exception and printing out an error message would be a better way to handle this, in my opinion.  

```bash
$ poetry2rye
created backup: /home/ssteiner/Downloads/rosegarden-23.12/.__p2r_backup_build_0
Traceback (most recent call last):
  File "/home/ssteiner/.local/bin/poetry2rye", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ssteiner/.local/pipx/venvs/poetry2rye/lib/python3.12/site-packages/poetry2rye/main.py", line 24, in main
    convert(project_path)
  File "/home/ssteiner/.local/pipx/venvs/poetry2rye/lib/python3.12/site-packages/poetry2rye/convert.py", line 26, in convert
    poetry_project = PoetryProject(project_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssteiner/.local/pipx/venvs/poetry2rye/lib/python3.12/site-packages/poetry2rye/project.py", line 73, in __init__
    assert (self.path / "pyproject.toml").exists(), "pyproject.toml not found"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: pyproject.toml not found
```

**Comment by nahco314** [comment]
I've been busy lately, so this is a delay, but I've changed the overall interface of the app (https://github.com/nahco314/poetry2rye/commit/b3e94e888993df3f4455f99cb8fd82547dbb4b8f).
